### ISSUE TITLE
Slow to connect

### ISSUE THREAD

**Issue by schneidersoft** [cortexm/pyswd#19]
I do not know if this is normal but it takes more than 10 seconds to connect for me.
```
import time
import libusb_package
import usb.core
import usb.backend.libusb1
libusb1_backend = usb.backend.libusb1.get_backend(find_library=libusb_package.find_library)

import swd

x = time.time()
dev = swd.Swd()
y = time.time()
print('CONNECTED in {} seconds'.format(y-x))
```

```
# py -3 swdspeedtest.py
CONNECTED in 12.987221956253052 seconds
```

I would like to get connection speed closer to 2 seconds or less.
Perhaps it is related to libusb not pyswd? Any suggestions?

**Comment by pavelrevak** [comment]
Hello, yes, this is probably related to libusb,
I never saw these long times in connecting
it is windows host ?
try run it with parameter
`swd.Swd(debug=4)`
it will print some info what is doing, yes this is not standard logging, it is something internal, try to look where is waiting

**Comment by schneidersoft** [comment]
Yes. Windows. It has somehow solved itself. I have no idea how. Perhaps an automatic update.
But now It is too fast hahaha.
```
import time
import libusb_package
import usb.core
import usb.backend.libusb1
libusb1_backend = usb.backend.libusb1.get_backend(find_library=libusb_package.find_library)

import swd

x = time.time()
dev = swd.Swd()
y = time.time()
print('CONNECTED in {} seconds'.format(y-x))

mcu = swd.CortexM(dev)

mcu.reset_halt()

#time.sleep(0.5)
mcu.set_reg('SP', 0)

```

Really amazing speed. Better than the official tools!
```
# py -3 swdspeedtest.py
CONNECTED in 0.06174516677856445 seconds
```

But a sleep is required to make it work. without sleep commands are executed to quickly and fail.
```
# py -3 swdspeedtest.py
CONNECTED in 0.08237195014953613 seconds
Traceback (most recent call last):
  File "C:\WORK\pyTest\swdspeedtest.py", line 19, in <module>
    mcu.set_reg('SP', 0)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\cortexm.py", line 65, in set_reg
    return self._swd.set_reg(CortexM._get_reg_index(reg), data)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\swd.py", line 83, in set_reg
    self._drv.set_reg(register, data)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\stlink\__init__.py", line 284, in set_reg
    _check_status(status)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\stlink\__init__.py", line 56, in _check_status
    raise StlinkException(_com.StlinkCom.STATUS.MESSAGES[status])
swd.stlink.StlinkException: Command error
```

Have you ever seen such issues before?

**Comment by schneidersoft** [comment]
With debug=4
```
#py -3 swdspeedtest.py
CONNECTED in 0.0608057975769043 seconds
Traceback (most recent call last):
  File "C:\WORK\pyTest\swdspeedtest.py", line 19, in <module>
    mcu.set_reg('SP', 0)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\cortexm.py", line 65, in set_reg
    return self._swd.set_reg(CortexM._get_reg_index(reg), data)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\swd.py", line 83, in set_reg
    self._drv.set_reg(register, data)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\stlink\__init__.py", line 284, in set_reg
    _check_status(status)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\stlink\__init__.py", line 56, in _check_status
    raise StlinkException(_com.StlinkCom.STATUS.MESSAGES[status])
swd.stlink.StlinkException: Command error

C:\WORK\pyTest>py -3 swdspeedtest.py
command: f1 80
USB:WR: f1 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00
USB:RD: 29 47 83 04 48 37
command: f5
USB:WR: f5 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
USB:RD: 02 00
command: f2 21
USB:WR: f2 21 00 00 00 00 00 00 00 00 00 00 00 00 00 00
command: f2 30 a3
USB:WR: f2 30 a3 00 00 00 00 00 00 00 00 00 00 00 00 00
USB:RD: 80 00
CONNECTED in 0.062102556228637695 seconds
command: f2 35 f0 ed 00 e0 03 00 5f a0
USB:WR: f2 35 f0 ed 00 e0 03 00 5f a0 00 00 00 00 00 00
USB:RD: 80 00
command: f2 35 fc ed 00 e0 01 00 00 00
USB:WR: f2 35 fc ed 00 e0 01 00 00 00 00 00 00 00 00 00
USB:RD: 80 00
command: f2 35 0c ed 00 e0 04 00 fa 05
USB:WR: f2 35 0c ed 00 e0 04 00 fa 05 00 00 00 00 00 00
USB:RD: 80 00
command: f2 34 0d 00 00 00 00
USB:WR: f2 34 0d 00 00 00 00 00 00 00 00 00 00 00 00 00
USB:RD: 08 00
Traceback (most recent call last):
  File "C:\WORK\pyTest\swdspeedtest.py", line 19, in <module>
    mcu.set_reg('SP', 0)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\cortexm.py", line 65, in set_reg
    return self._swd.set_reg(CortexM._get_reg_index(reg), data)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\swd.py", line 83, in set_reg
    self._drv.set_reg(register, data)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\stlink\__init__.py", line 284, in set_reg
    _check_status(status)
  File "C:\Users\H341741\AppData\Local\Programs\Python\Python310\lib\site-packages\swd\stlink\__init__.py", line 56, in _check_status
    raise StlinkException(_com.StlinkCom.STATUS.MESSAGES[status])
swd.stlink.StlinkException: Command error
```

**Comment by pavelrevak** [comment]
have you latest version of FW in STLINK ?
this error is exactly "JTAG_CMD_ERROR" this probably mean that STLINK don't know this command for setting registers.. or something else

**Comment by schneidersoft** [comment]
This seems to be a problem related to windows, security settings, and libusb.
One Linux it is working fine...
