### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by simonnilsson** [cortexm/pyswd#3]
Hi, I'm getting an error while using the read_mem() function

I think the error happens when using read_mem() with a (size > 4) and (size % 4 != 0)

**ST-Link version:** ST-Link/V2-1 V2J28M18

## Code to reproduce

```
import swd
import time

dev = swd.Swd()

while True:
    print('reading')
    data = list(dev.read_mem(0x20000000, 5))
    print(data)
    time.sleep(1)
```

First read is successful but Exception is thrown at second read. ST-Link needs to be unpluged and repluged to make it work again.

## Traceback

```
Traceback (most recent call last):
  File "swd\stlinkcom.py", line 77, in write
    count = self._dev.write(self.PIPE_OUT, data, tout)
  File "Python\Python36-32\lib\site-packages\usb\core.py", line 948, in write
    self.__get_timeout(timeout)
  File "Python\Python36-32\lib\site-packages\usb\backend\libusb1.py", line 824, in bulk_write
    timeout)
  File "Python\Python36-32\lib\site-packages\usb\backend\libusb1.py", line 920, in __write
    _check(retval)
  File "Python\Python36-32\lib\site-packages\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 10060] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    data = list(dev.read_mem(0x20000000, 5))
  File "swd\swd.py", line 147, in read_mem
    yield from self._drv.read_mem8(address, chunk_size)
  File "swd\_log.py", line 29, in wrapper
    ret = func(*args, **kwargs)
  File "swd\stlink.py", line 370, in read_mem8
    return self._com.xfer(cmd, rx_length=size)
  File "swd\_log.py", line 29, in wrapper
    ret = func(*args, **kwargs)
  File "swd\stlinkcom.py", line 185, in xfer
    self._dev.write(command, tout)
  File "swd\_log.py", line 29, in wrapper
    ret = func(*args, **kwargs)
  File "swd\stlinkcom.py", line 80, in write
    raise StlinkComException("USB Error: %s" % err)
swd.stlinkcom.StlinkComException: USB Error: [Errno 10060] Operation timed out
```

**Comment by pavelrevak** [comment]
Hello, try version from branch issue/3

**Comment by simonnilsson** [comment]
Works great, thanks.
